//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceUtils.OAAttachment {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://OAAttach/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://OAAttach/", ConfigurationName="OAAttachment.AttMain")]
    public interface AttMain {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://OAAttach/AttMain/encryptRequest", ReplyAction="http://OAAttach/AttMain/encryptResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(InvoiceUtils.OAAttachment.Exception), Action="http://OAAttach/AttMain/encrypt/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InvoiceUtils.OAAttachment.encryptResponse encrypt(InvoiceUtils.OAAttachment.encryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://OAAttach/AttMain/encryptRequest", ReplyAction="http://OAAttach/AttMain/encryptResponse")]
        System.Threading.Tasks.Task<InvoiceUtils.OAAttachment.encryptResponse> encryptAsync(InvoiceUtils.OAAttachment.encryptRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://OAAttach/AttMain/decryptRequest", ReplyAction="http://OAAttach/AttMain/decryptResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(InvoiceUtils.OAAttachment.Exception), Action="http://OAAttach/AttMain/decrypt/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InvoiceUtils.OAAttachment.decryptResponse decrypt(InvoiceUtils.OAAttachment.decryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://OAAttach/AttMain/decryptRequest", ReplyAction="http://OAAttach/AttMain/decryptResponse")]
        System.Threading.Tasks.Task<InvoiceUtils.OAAttachment.decryptResponse> decryptAsync(InvoiceUtils.OAAttachment.decryptRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://OAAttach/AttMain/sayHelloWorldFromRequest", ReplyAction="http://OAAttach/AttMain/sayHelloWorldFromResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InvoiceUtils.OAAttachment.sayHelloWorldFromResponse sayHelloWorldFrom(InvoiceUtils.OAAttachment.sayHelloWorldFromRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://OAAttach/AttMain/sayHelloWorldFromRequest", ReplyAction="http://OAAttach/AttMain/sayHelloWorldFromResponse")]
        System.Threading.Tasks.Task<InvoiceUtils.OAAttachment.sayHelloWorldFromResponse> sayHelloWorldFromAsync(InvoiceUtils.OAAttachment.sayHelloWorldFromRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="encrypt", WrapperNamespace="http://OAAttach/", IsWrapped=true)]
    public partial class encryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://OAAttach/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://OAAttach/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://OAAttach/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public encryptRequest() {
        }
        
        public encryptRequest(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="encryptResponse", WrapperNamespace="http://OAAttach/", IsWrapped=true)]
    public partial class encryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://OAAttach/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public encryptResponse() {
        }
        
        public encryptResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="decrypt", WrapperNamespace="http://OAAttach/", IsWrapped=true)]
    public partial class decryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://OAAttach/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://OAAttach/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public decryptRequest() {
        }
        
        public decryptRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="decryptResponse", WrapperNamespace="http://OAAttach/", IsWrapped=true)]
    public partial class decryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://OAAttach/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public decryptResponse() {
        }
        
        public decryptResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sayHelloWorldFrom", WrapperNamespace="http://OAAttach/", IsWrapped=true)]
    public partial class sayHelloWorldFromRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://OAAttach/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public sayHelloWorldFromRequest() {
        }
        
        public sayHelloWorldFromRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sayHelloWorldFromResponse", WrapperNamespace="http://OAAttach/", IsWrapped=true)]
    public partial class sayHelloWorldFromResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://OAAttach/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sayHelloWorldFromResponse() {
        }
        
        public sayHelloWorldFromResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AttMainChannel : InvoiceUtils.OAAttachment.AttMain, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AttMainClient : System.ServiceModel.ClientBase<InvoiceUtils.OAAttachment.AttMain>, InvoiceUtils.OAAttachment.AttMain {
        
        public AttMainClient() {
        }
        
        public AttMainClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AttMainClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AttMainClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AttMainClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InvoiceUtils.OAAttachment.encryptResponse InvoiceUtils.OAAttachment.AttMain.encrypt(InvoiceUtils.OAAttachment.encryptRequest request) {
            return base.Channel.encrypt(request);
        }
        
        public bool encrypt(string arg0, string arg1, string arg2) {
            InvoiceUtils.OAAttachment.encryptRequest inValue = new InvoiceUtils.OAAttachment.encryptRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            InvoiceUtils.OAAttachment.encryptResponse retVal = ((InvoiceUtils.OAAttachment.AttMain)(this)).encrypt(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceUtils.OAAttachment.encryptResponse> InvoiceUtils.OAAttachment.AttMain.encryptAsync(InvoiceUtils.OAAttachment.encryptRequest request) {
            return base.Channel.encryptAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceUtils.OAAttachment.encryptResponse> encryptAsync(string arg0, string arg1, string arg2) {
            InvoiceUtils.OAAttachment.encryptRequest inValue = new InvoiceUtils.OAAttachment.encryptRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((InvoiceUtils.OAAttachment.AttMain)(this)).encryptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InvoiceUtils.OAAttachment.decryptResponse InvoiceUtils.OAAttachment.AttMain.decrypt(InvoiceUtils.OAAttachment.decryptRequest request) {
            return base.Channel.decrypt(request);
        }
        
        public bool decrypt(string arg0, string arg1) {
            InvoiceUtils.OAAttachment.decryptRequest inValue = new InvoiceUtils.OAAttachment.decryptRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            InvoiceUtils.OAAttachment.decryptResponse retVal = ((InvoiceUtils.OAAttachment.AttMain)(this)).decrypt(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceUtils.OAAttachment.decryptResponse> InvoiceUtils.OAAttachment.AttMain.decryptAsync(InvoiceUtils.OAAttachment.decryptRequest request) {
            return base.Channel.decryptAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceUtils.OAAttachment.decryptResponse> decryptAsync(string arg0, string arg1) {
            InvoiceUtils.OAAttachment.decryptRequest inValue = new InvoiceUtils.OAAttachment.decryptRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((InvoiceUtils.OAAttachment.AttMain)(this)).decryptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InvoiceUtils.OAAttachment.sayHelloWorldFromResponse InvoiceUtils.OAAttachment.AttMain.sayHelloWorldFrom(InvoiceUtils.OAAttachment.sayHelloWorldFromRequest request) {
            return base.Channel.sayHelloWorldFrom(request);
        }
        
        public string sayHelloWorldFrom(string arg0) {
            InvoiceUtils.OAAttachment.sayHelloWorldFromRequest inValue = new InvoiceUtils.OAAttachment.sayHelloWorldFromRequest();
            inValue.arg0 = arg0;
            InvoiceUtils.OAAttachment.sayHelloWorldFromResponse retVal = ((InvoiceUtils.OAAttachment.AttMain)(this)).sayHelloWorldFrom(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvoiceUtils.OAAttachment.sayHelloWorldFromResponse> InvoiceUtils.OAAttachment.AttMain.sayHelloWorldFromAsync(InvoiceUtils.OAAttachment.sayHelloWorldFromRequest request) {
            return base.Channel.sayHelloWorldFromAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvoiceUtils.OAAttachment.sayHelloWorldFromResponse> sayHelloWorldFromAsync(string arg0) {
            InvoiceUtils.OAAttachment.sayHelloWorldFromRequest inValue = new InvoiceUtils.OAAttachment.sayHelloWorldFromRequest();
            inValue.arg0 = arg0;
            return ((InvoiceUtils.OAAttachment.AttMain)(this)).sayHelloWorldFromAsync(inValue);
        }
    }
}
